version: '3'
services:
  solr:
    image: solr:${SOLR_VERSION}
    container_name: ${SOLR_CORE_NAME}-solr
    restart: on-failure
    ports:
      - "20083:8983"
    volumes:
      - ./etc/solr/config/configsets/${SOLR_CONFIGSET_NAME}:/opt/solr/server/solr/configsets/${SOLR_CONFIGSET_NAME}
      - ./data/solr/data:/var/solr/data
      - ./log/solr:/var/solr/logs
    entrypoint:
      - solr-precreate
      - ${SOLR_CORE_NAME}
      - /opt/solr/server/solr/configsets/${SOLR_CONFIGSET_NAME}
